"""armsmith.rules.base — rule descriptors, findings, and the detector registry.

A rule is described by a YAML descriptor (id, kind, fix_generator,
expected_gain_range, citation_url, confidence — see ``rules/packs/*.yaml``)
and implemented by a detector function registered under the rule id.

Honesty contract:
* ``expected_gain_range`` is an ESTIMATE sourced from the citation — it is
  never presented as a measurement.  Only the reproduce gate produces claims.
* Detectors that lack the observations they need return ``SKIPPED`` with the
  missing probe names — they never guess.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Protocol

from ..probes import Probe, ProbeMissing

__all__ = [
    "RuleSpec",
    "Fix",
    "FindingStatus",
    "Finding",
    "Detector",
    "DETECTORS",
    "register",
    "run_rule",
    "CONFIDENCE_RANK",
]

CONFIDENCE_RANK = {"high": 0, "medium": 1, "low": 2}


@dataclass(frozen=True)
class RuleSpec:
    """Parsed YAML descriptor for one rule."""

    id: str
    title: str
    kind: str                       # "static" | "probe" | "hybrid"
    requires: tuple[str, ...]       # probe kinds the detector needs
    summary: str
    fix_generator: str              # human description of the fix template
    expected_gain_range: tuple[float, float]  # ESTIMATE multipliers (see gain_note)
    gain_note: str
    citation_url: str
    confidence: str                 # high | medium | low
    #: Arm Learning Path that teaches this fix by hand (the rubric's
    #: "learning-ready content"). None where no strong Arm LP exists — those
    #: rules honestly cite only their upstream ``citation_url``.
    learning_path: str | None = None
    #: The migration template proper: the smallest honest before/after edit for
    #: this anti-pattern, and the language to fence it in. A card without these
    #: is an index entry, not a template — you cannot paste a paragraph. Both
    #: must be present or neither is rendered.
    before: str | None = None
    after: str | None = None
    snippet_lang: str = "text"

    @property
    def has_snippet(self) -> bool:
        return bool(self.before and self.after)

    def gain_midpoint(self) -> float:
        lo, hi = self.expected_gain_range
        return (lo + hi) / 2.0

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "kind": self.kind,
            "requires": list(self.requires),
            "summary": self.summary,
            "fix_generator": self.fix_generator,
            "expected_gain_range": list(self.expected_gain_range),
            "gain_note": self.gain_note,
            "citation_url": self.citation_url,
            "learning_path": self.learning_path,
            "confidence": self.confidence,
            "before": self.before,
            "after": self.after,
            "snippet_lang": self.snippet_lang,
        }


@dataclass(frozen=True)
class Fix:
    """A deterministic fix proposal generated by a detector.

    ``patch`` is a concrete file edit / snippet when one can be produced
    deterministically; ``commands`` are suggested shell commands.  Neither is
    ever auto-applied without passing the reproduce gate.
    """

    rule_id: str
    kind: str          # dockerfile_edit|env_change|build_flag|pip_pin|config_patch|code_suggestion|quant_swap|ci_patch
    description: str
    patch: str | None = None
    commands: tuple[str, ...] = ()

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "kind": self.kind,
            "description": self.description,
            "patch": self.patch,
            "commands": list(self.commands),
        }


class FindingStatus(str, Enum):
    MATCHED = "matched"    # anti-pattern present; fix proposed
    CLEAN = "clean"        # checked and not present
    SKIPPED = "skipped"    # could not check (missing repo/probe data)


@dataclass(frozen=True)
class Finding:
    rule_id: str
    status: FindingStatus
    evidence: tuple[str, ...] = ()
    locations: tuple[str, ...] = ()   # file:line or probe kinds
    fix: Fix | None = None
    skipped_reason: str | None = None

    @property
    def matched(self) -> bool:
        return self.status is FindingStatus.MATCHED

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "status": self.status.value,
            "evidence": list(self.evidence),
            "locations": list(self.locations),
            "fix": self.fix.to_dict() if self.fix else None,
            "skipped_reason": self.skipped_reason,
        }


class Detector(Protocol):
    def __call__(self, repo: Path | None, probe: Probe | None, spec: RuleSpec) -> Finding: ...


#: rule id → detector callable (populated by @register in detectors/*).
DETECTORS: dict[str, Detector] = {}


def register(rule_id: str) -> Callable[[Detector], Detector]:
    def deco(fn: Detector) -> Detector:
        if rule_id in DETECTORS:
            raise ValueError(f"detector for {rule_id} registered twice")
        DETECTORS[rule_id] = fn
        return fn
    return deco


def skipped(spec: RuleSpec, reason: str) -> Finding:
    return Finding(rule_id=spec.id, status=FindingStatus.SKIPPED, skipped_reason=reason)


def clean(spec: RuleSpec, evidence: list[str] | None = None) -> Finding:
    return Finding(
        rule_id=spec.id,
        status=FindingStatus.CLEAN,
        evidence=tuple(evidence or ()),
    )


def run_rule(spec: RuleSpec, repo: Path | None, probe: Probe | None) -> Finding:
    """Run one rule with skip-instead-of-guess semantics."""
    detector = DETECTORS.get(spec.id)
    if detector is None:
        return skipped(spec, f"no detector registered for {spec.id}")

    if spec.kind in ("static", "hybrid") and repo is None:
        return skipped(spec, "static detector needs a repo checkout (none provided)")

    if spec.requires:
        if probe is None:
            return skipped(spec, f"needs probes {list(spec.requires)} but no probe backend given")
        missing = [k for k in spec.requires if not probe.has(k)]
        if missing:
            return skipped(spec, f"probe data not recorded: {missing}")

    try:
        return detector(repo, probe, spec)
    except ProbeMissing as exc:
        return skipped(spec, f"probe data missing at read time: {exc}")
