"""armsmith.gguf — minimal GGUF header/metadata reader (+ stub writer).

Reads just enough of the GGUF container format to answer R5's question:
*which quant format is this model?* — magic, version, tensor/kv counts, and
the string/scalar metadata KVs (``general.architecture``,
``general.file_type``).  Arrays are skipped structurally.

The stub writer exists so the test fixtures under ``fixtures/`` are
generated by auditable code in this repo (see scripts/make_gguf_fixtures.py)
instead of opaque committed blobs.

Format reference: https://github.com/ggml-org/ggml/blob/master/docs/gguf.md
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from pathlib import Path

__all__ = ["GgufHeader", "GgufError", "read_header", "build_stub", "FILE_TYPE_NAMES"]

MAGIC = b"GGUF"

# gguf metadata value types
T_UINT8, T_INT8, T_UINT16, T_INT16, T_UINT32, T_INT32 = 0, 1, 2, 3, 4, 5
T_FLOAT32, T_BOOL, T_STRING, T_ARRAY, T_UINT64, T_INT64, T_FLOAT64 = 6, 7, 8, 9, 10, 11, 12

_SCALAR_FMT = {
    T_UINT8: "<B", T_INT8: "<b", T_UINT16: "<H", T_INT16: "<h",
    T_UINT32: "<I", T_INT32: "<i", T_FLOAT32: "<f", T_BOOL: "<B",
    T_UINT64: "<Q", T_INT64: "<q", T_FLOAT64: "<d",
}

#: llama_ftype enum → human name (core values; llama.cpp llama.h).
FILE_TYPE_NAMES: dict[int, str] = {
    0: "F32", 1: "F16", 2: "Q4_0", 3: "Q4_1", 7: "Q8_0", 8: "Q5_0", 9: "Q5_1",
    10: "Q2_K", 11: "Q3_K_S", 12: "Q3_K_M", 13: "Q3_K_L", 14: "Q4_K_S",
    15: "Q4_K_M", 16: "Q5_K_S", 17: "Q5_K_M", 18: "Q6_K",
}

K_QUANT_CODES = frozenset(range(10, 19))
Q4_0_CODE = 2


class GgufError(ValueError):
    pass


@dataclass
class GgufHeader:
    version: int
    n_tensors: int
    n_kv: int
    metadata: dict[str, object] = field(default_factory=dict)

    @property
    def file_type_code(self) -> int | None:
        v = self.metadata.get("general.file_type")
        return int(v) if isinstance(v, int) else None

    @property
    def file_type_name(self) -> str | None:
        code = self.file_type_code
        if code is None:
            return None
        return FILE_TYPE_NAMES.get(code, f"unknown({code})")

    @property
    def architecture(self) -> str | None:
        v = self.metadata.get("general.architecture")
        return str(v) if v is not None else None


class _Reader:
    def __init__(self, data: bytes):
        self.data = data
        self.off = 0

    def take(self, n: int) -> bytes:
        if self.off + n > len(self.data):
            raise GgufError(
                f"truncated GGUF data: need {n} bytes at offset {self.off}, "
                f"have {len(self.data) - self.off}"
            )
        chunk = self.data[self.off : self.off + n]
        self.off += n
        return chunk

    def scalar(self, fmt: str):
        size = struct.calcsize(fmt)
        return struct.unpack(fmt, self.take(size))[0]

    def string(self) -> str:
        n = self.scalar("<Q")
        return self.take(n).decode("utf-8", errors="replace")


def _read_value(r: _Reader, vtype: int):
    if vtype in _SCALAR_FMT:
        val = r.scalar(_SCALAR_FMT[vtype])
        return bool(val) if vtype == T_BOOL else val
    if vtype == T_STRING:
        return r.string()
    if vtype == T_ARRAY:
        elem_type = r.scalar("<I")
        count = r.scalar("<Q")
        return [_read_value(r, elem_type) for _ in range(count)]
    raise GgufError(f"unknown GGUF value type {vtype}")


def read_header(data: bytes, max_kv: int = 64) -> GgufHeader:
    """Parse the GGUF header + metadata KVs from raw bytes."""
    r = _Reader(data)
    if r.take(4) != MAGIC:
        raise GgufError("not a GGUF file (bad magic)")
    version = r.scalar("<I")
    if version < 2:
        raise GgufError(f"unsupported GGUF version {version}")
    n_tensors = r.scalar("<Q")
    n_kv = r.scalar("<Q")
    if n_kv > max_kv:
        raise GgufError(f"refusing to parse {n_kv} KVs (max {max_kv} for header stubs)")
    meta: dict[str, object] = {}
    for _ in range(n_kv):
        key = r.string()
        vtype = r.scalar("<I")
        meta[key] = _read_value(r, vtype)
    return GgufHeader(version=version, n_tensors=n_tensors, n_kv=n_kv, metadata=meta)


def read_header_file(path: Path, max_bytes: int = 65536) -> GgufHeader:
    return read_header(Path(path).read_bytes()[:max_bytes])


# ---------------------------------------------------------------------------
# Stub writer (fixture generation only — never fabricates a real model)
# ---------------------------------------------------------------------------

def _write_string(s: str) -> bytes:
    b = s.encode("utf-8")
    return struct.pack("<Q", len(b)) + b


def build_stub(
    file_type: int,
    architecture: str = "llama",
    version: int = 3,
    n_tensors: int = 0,
    extra_meta: dict[str, int] | None = None,
) -> bytes:
    """Build a minimal, clearly-synthetic GGUF *header* (no tensor data).

    Used exclusively to author test fixtures: a valid header carrying
    general.architecture, general.file_type and a synthetic marker KV.
    """
    meta: list[tuple[str, int | str]] = [
        ("general.architecture", architecture),
        ("general.file_type", int(file_type)),
        ("armsmith.synthetic_fixture", 1),  # provenance marker: NOT a real model
    ]
    for k, v in (extra_meta or {}).items():
        meta.append((k, int(v)))

    out = bytearray()
    out += MAGIC
    out += struct.pack("<I", version)
    out += struct.pack("<Q", n_tensors)
    out += struct.pack("<Q", len(meta))
    for key, val in meta:
        out += _write_string(key)
        if isinstance(val, str):
            out += struct.pack("<I", T_STRING)
            out += _write_string(val)
        else:
            out += struct.pack("<I", T_UINT32)
            out += struct.pack("<I", val)
    return bytes(out)
